// <auto-generated />
using System;
using BibliotecaVirtual.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaVirtual.Migrations
{
    [DbContext(typeof(BibliotecaDbContext))]
    partial class BibliotecaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaVirtual.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BibliotecaVirtual.Moldels.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Autor");

                    b.HasIndex("Categoria");

                    b.HasIndex("Titulo");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Miguel de Cervantes",
                            Categoria = "Literatura Clásica",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Don Quijote de La Mancha"
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Gabriel García Márquez",
                            Categoria = "Literatura Latinoamericana",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Cien Años de Soledad"
                        },
                        new
                        {
                            Id = 3,
                            Autor = "George Orwell",
                            Categoria = "Ciencia Ficción",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Antoine de Saint-Exupéry",
                            Categoria = "Literatura Juvenil",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "El Principito"
                        },
                        new
                        {
                            Id = 5,
                            Autor = "Luis Joyanes Aguilar",
                            Categoria = "Informática",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Fundamentos de Programación"
                        },
                        new
                        {
                            Id = 6,
                            Autor = "Thomas H. Cormen",
                            Categoria = "Informática",
                            Estado = 2,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Estructura de Datos y Algoritmos"
                        },
                        new
                        {
                            Id = 7,
                            Autor = "Abraham Silberschatz",
                            Categoria = "Informática",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Base de Datos: Diseño y Implementación"
                        },
                        new
                        {
                            Id = 8,
                            Autor = "Jorge Orlando Melo",
                            Categoria = "Historia",
                            Estado = 3,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Historia de Colombia"
                        },
                        new
                        {
                            Id = 9,
                            Autor = "Michael Spivak",
                            Categoria = "Matemáticas",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Cálculo Diferencial e Integral"
                        },
                        new
                        {
                            Id = 10,
                            Autor = "Hugh D. Young",
                            Categoria = "Física",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Física Universitaria"
                        },
                        new
                        {
                            Id = 11,
                            Autor = "Cristiano Ronaldo",
                            Categoria = "Deporte",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "El Método Ronaldo"
                        },
                        new
                        {
                            Id = 12,
                            Autor = "Tim S. Grover",
                            Categoria = "Deporte",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Relentless: From Good to Great to Unstoppable"
                        },
                        new
                        {
                            Id = 13,
                            Autor = "Joyanes Aguilar",
                            Categoria = "Programación",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Programación en C# Paso a Paso"
                        },
                        new
                        {
                            Id = 14,
                            Autor = "Robert C. Martin",
                            Categoria = "Programación",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Clean Code: A Handbook of Agile Software Craftsmanship"
                        },
                        new
                        {
                            Id = 15,
                            Autor = "Stuart Russell",
                            Categoria = "Programación",
                            Estado = 3,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Introducción a la Inteligencia Artificial"
                        },
                        new
                        {
                            Id = 16,
                            Autor = "Karlos Arguiñano",
                            Categoria = "Cocina",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Cocina Fácil para Estudiantes"
                        },
                        new
                        {
                            Id = 17,
                            Autor = "Julia Child",
                            Categoria = "Cocina",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Mastering the Art of French Cooking"
                        },
                        new
                        {
                            Id = 18,
                            Autor = "Ibán Yarza",
                            Categoria = "Cocina",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Pan Casero: Recetas Tradicionales"
                        },
                        new
                        {
                            Id = 19,
                            Autor = "Nancy Clark",
                            Categoria = "Deporte",
                            Estado = 2,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Nutrición y Dietética Deportiva"
                        },
                        new
                        {
                            Id = 20,
                            Autor = "Jamie Oliver",
                            Categoria = "Cocina",
                            Estado = 1,
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Recetas Saludables para Cada Día"
                        });
                });

            modelBuilder.Entity("BibliotecaVirtual.Moldels.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("BibliotecaVirtual.Moldels.Prestamo", b =>
                {
                    b.HasOne("BibliotecaVirtual.Moldels.Libro", "Libro")
                        .WithMany("Prestamos")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaVirtual.Models.Usuario", "Usuario")
                        .WithMany("Prestamos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BibliotecaVirtual.Models.Usuario", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("BibliotecaVirtual.Moldels.Libro", b =>
                {
                    b.Navigation("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
